### ISSUE TITLE
Order in the sequence

### ISSUE THREAD

**Issue by blake41** [learn-co-curriculum/rails-blog-associations-validations#10]
This lab seems a little out of place in at the end of the sequence.  This is more like a beginner lab after you've build a scaffold.  you're doing basic many <-> many associations, and simple validations

**Comment by AnnJohn** [comment]
@pletcher if you think this should be moved around int he full stack track, feel free to move it. or you can  just close the issue. thanks.

**Comment by pletcher** [comment]
I moved it to the end of the validations unit.
<img width="610" alt="screen shot 2016-04-25 at 4 21 59 pm" src="https://cloud.githubusercontent.com/assets/2015049/14797669/daa1e0ea-0b01-11e6-8b1f-6168140ee687.png">
