### ISSUE TITLE
broken spec_helper?

### ISSUE THREAD

**Issue by jnoconor** [learn-co-curriculum/rails-blog-associations-validations#13]
This block
https://github.com/learn-co-curriculum/rails-blog-associations-validations/blob/master/spec/spec_helper.rb#L26

conflicts with this
https://github.com/learn-co-curriculum/rails-blog-associations-validations/blob/master/spec/01_models/01_user_spec.rb#L18

given that Users have to have unique names. Removing `config.before(:each)` from the spec_helper allows correct code to pass the tests.

**Comment by authorbeard** [comment]
This is still not fixed.
