### ISSUE TITLE
need to create User, Tag controllers/routes/etc unclear for lab as-presented

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/rails-blog-associations-validations#17]
Under the Migrations, Associations, and Routes heading for this lab, there are instructions to create controllers for User and Tag, along with 'appropriate routes.'  These controllers aren't actually needed, though, to pass existing lab specs.  Would it be possible to introduce minimal features testing for User and Tag, to justify the files and routes?  Or--alternatively--to clarify the reason(s) for creating these files, routes in the readme?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
