### ISSUE TITLE
Lab Missing manifest.js and rails_helper.rb

### ISSUE THREAD

**Issue by afteralec** [learn-co-curriculum/rails-blog-associations-validations#21]
Hi! This lab is missing app/assets/config/manifest.js (seems to be required by the `railties` gem)  and missing `rails_helper.rb`. I was able to solve this by creating a blank `app/assets/config/manifest.js` file and copy+pasting the `rails_helper.rb` file from the has-many-through-forms-rails lab, and the rspec tests now seem to be running. Thanks!

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
