### ISSUE TITLE
Tests pass, but post doesn't save

### ISSUE THREAD

**Issue by isphinxs** [learn-co-curriculum/rails-blog-associations-validations#22]
The spec tests all pass, but when running the Rails server, creating a post fails when selecting at least one tag.  Tag is failing validation, I think possibly because the uniqueness validation thinks that a new tag is being created.  Here are the error details: 

```
@details={:tags=>[{:error=>:invalid}]},
@messages={:tags=>["is invalid"]}
```
Ask a Question couldn't help me, so I wanted to flag this.

**Comment by ihollander** [comment]
Hi @isphinxs - thanks for raising this issue and apologies that no one responded sooner! I wasn't able to reproduce the issue you experienced so I'm closing this issue. If you're curious to see an alternative approach to the one you came up with, you can view the [solution branch](https://github.com/learn-co-curriculum/rails-blog-associations-validations/tree/solution).
